## aasasdsdasd
POST http://localhost:8080/login
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "testers"
}



### Send asdasd request with json body
POST http://localhost:8080/signup
Content-Type: application/json

{
  "email": "baba@test.com",
  "password": "baba"
}



### Send POST request with json body
POST http://localhost:8000/tasks
Content-Type: application/json
Authorization: Bearer abc

{
  "text": "baba text",
  "title": "baba taaaitle"
}