apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-pv
spec:
  volumeName: host-pv
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi